version: '3.11'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Backend port
      - "3000:3000"  # Frontend port
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:lbo_dev@postgres/postgres

  postgres:
    container_name: postgres_dev
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lbo_dev
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
