"""empty message

Revision ID: 7fd9604d47b8
Revises: 0da8adc58ab7
Create Date: 2023-11-14 14:56:54.974687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7fd9604d47b8'
down_revision: Union[str, None] = '0da8adc58ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('customer', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project', sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project', sa.Column('po_issue_date', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('po_delivery_date', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('po_value', sa.Float(), nullable=False))
    op.add_column('project', sa.Column('po_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'po_currency')
    op.drop_column('project', 'po_value')
    op.drop_column('project', 'po_delivery_date')
    op.drop_column('project', 'po_issue_date')
    op.drop_column('project', 'po_number')
    op.drop_column('project', 'customer')
    # ### end Alembic commands ###
