"""empty message

Revision ID: 869c9124393b
Revises: 922d5218888c
Create Date: 2023-11-20 16:10:42.561994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '869c9124393b'
down_revision: Union[str, None] = '922d5218888c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'DRAFT'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
