"""empty message

Revision ID: 922d5218888c
Revises: 7fd9604d47b8
Create Date: 2023-11-16 14:51:37.311873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '922d5218888c'
down_revision: Union[str, None] = '7fd9604d47b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_project_customer'), 'project', ['customer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_customer'), table_name='project')
    op.drop_column('project', 'uid')
    # ### end Alembic commands ###
